language: php

services:
  - mysql

php:
    - 5.6
    - 7

env:
  - SYMFONY_VERSION=2.8.*

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer self-update
  - composer install

script: phpunit -c app

matrix:
  allow_failures:
    - env: SYMFONY_VERSION=dev-master
