#WIP ROUTES
ddxdr_kraken_history:
    path:     /kraken/history
    methods: [ get ]
    defaults: { _controller: DdxDrWebBundle:Index:krakenHistory }
    
ddxdr_kraken_ohlc:
    path:     /kraken/ohlc
    methods: [ get ]
    defaults: { _controller: DdxDrWebBundle:Index:krakenOHLC }
    
#DEFINIVE ROUTES
ddxdr_marketsIndex:
    path:   /markets
    methods:    [ get ]
    defaults : { _controller: DdxDrWebBundle:Market:marketsIndex }
       

ddxdr_index:
    path:     /
    methods: [ get ]
    defaults: { _controller: DdxDrWebBundle:Index:index }
