<?php

namespace Dr\StrategyBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CrunchedDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CrunchedDataRepository extends EntityRepository
{
}
