<?php

namespace Dr\MarketBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OrderBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderBookRepository extends EntityRepository
{
}
