services:
    dr.refresher:
        class: Dr\ReaderBundle\Service\RefresherService
        arguments:
            markets:
              - "@dr.kraken"

    dr.kraken:
        class: Dr\ReaderBundle\Service\KrakenMarketService
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            tradeService: "@dr.trade"
            tradingPairService: "@dr.tradingpair"
            parameters : ['%kraken%']

    dr.helper:
        class: Dr\ReaderBundle\Service\BaseHelper
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            tradeService: "@dr.trade"
            tradingPairService: "@dr.tradingpair"
            krakenMarketService: "@dr.kraken"
            filterService: "@dr.filters"
