# WebBundle:routing.yml
app_homepage:
    path:     /
    defaults: { _controller: WebBundle:Home:index }


# Markets
dr_market_list:
    path: /markets
    defaults: { _controller: WebBundle:Market:list}

dr_market_show:
    path: /market/{market_id}
    defaults: { _controller: WebBundle:Market:show}
    requirements:
      market_id: \d+

dr_tradingpair_show:
    path: /pair/{tradingPair_id}
    defaults: { _controller: WebBundle:TradingPair:show}
    requirements:
      tradingPair_id: \d+


# Settings
  #assets
dr_settings_asset:
    path: /settings/asset
    defaults: { _controller: WebBundle:Settings:asset}

dr_settings_asset_new:
    path: /settings/new
    defaults: { _controller: WebBundle:Settings:newAsset}

dr_settings_asset_edit:
    path: /settings/asset/edit/{asset_id}
    defaults: { _controller: WebBundle:Settings:editAsset}
    requirements:
      asset_id: \d+

  # refresher
dr_settings_refresher:
    path: /settings/refresher
    defaults: { _controller: WebBundle:Settings:refresher }


# Charts
dr_chart_ohlc:
    path: /chart/ohlc/{tradingPair_id}
    defaults: { _controller: WebBundle:Chart:tradeHistoryOHLC}
    requirements:
      tradingPair_id: \d+


# Strategy
dr_strategy_list:
    path: /strategies
    defaults: { _controller: WebBundle:Strategy:list }

dr_strategy_add:
    path: /strategies/new
    defaults: { _controller: WebBundle:Strategy:add }

dr_strategy_show:
    path: /strategy/{strategy_id}
    defaults: { _controller: WebBundle:Strategy:show }
    requirements:
      strategy_id: \d+

dr_strategy_edit:
    path: /strategies/{strategy_id}/edit
    defaults: { _controller: WebBundle:Strategy:edit }
    requirements:
      strategy_id: \d+

dr_strategy_add_indicator:
    path: /strategies/{strategy_id}/indicator/add
    defaults: { _controller: WebBundle:Strategy:addIndicator }
    requirements:
      strategy_id: \d+


# Profile
avanzu_admin_profile:
    path: /profile

avanzu_admin_logout:
    path: /logout

# Tasks
avanzu_admin_all_tasks:
    path: /tasks/
avanzu_admin_show_task:
    path: /tasks/{taskid}/

# Notifications
avanzu_admin_all_notifications:
    path: /notifications/
avanzu_admin_show_notification:
    path: /notifications/{notifyid}/
